package Chain_of_Responsibility;

import org.junit.Test;

/**
 * Created by dylanb on 16/03/2018.
 */
public class RunCalcChainTest {
    @Test
    public void main() throws Exception {
    }

}